### ISSUE TITLE
Error in PDF generation when there is any "#" character in the HTML

### ISSUE THREAD

**Issue by juliabpp** [christopherdro/react-native-html-to-pdf#104]
This is happening in Android 8.0.1 and 8.1 versions from what I tested. It is not happening on Android 9.0.

**Comment by brognilucas** [comment]
> This is happening in Android 8.0.1 and 8.1 versions from what I tested. It is not happening on Android 9.0.
Same problem Here. In these moment, when I need pass any color as hex I converting to RGB.

**Comment by louiszawadzki** [comment]
My understanding is that it is happening when the installed version of Chrome is > 71.

On devices running Chrome up to version 71, you could see this log when generating a PDF with '#' characters:
```
chromium  I  [INFO:CONSOLE(0)] "Using unescaped '#' characters in a data URI body is deprecated and will be removed in M71, around December 2018. Please use '%23' instead. See https://www.chromestatus.com/features/5656049583390720 for more details.", source:  (0)
```

By looking at https://www.chromestatus.com/features/5656049583390720, it has indeed been removed in Chrome for Android version 72. 

Moreover, I have 2 Galaxy Tab S2 with same Android version (7.0), one has Chrome 71, the other 72 and the bug is only happening on the one running Chrome 72.

**Comment by rogerionj** [comment]
Hi, any solutiom?  Same problem.

**Comment by Great-hijack** [comment]
Same issue for me.
Is there any solution?
