### ISSUE TITLE
Build failed: Could not find com.tom_roush:pdfbox-android:1.8.10.0

### ISSUE THREAD

**Issue by Pranat-morphosis** [christopherdro/react-native-html-to-pdf#235]
Follow the installation with a new project and got this issue
OS: Windows 10
Platform: Android

![Screenshot 2021-09-06 180255](https://user-images.githubusercontent.com/84968167/132208158-480b31b1-71a8-402a-8004-7a5cda2a364b.png)

**Comment by wbroek** [comment]
@Pranat-morphosis it cannot find the Android dependency because jCenter has been removed in the latest react native version as a repository of depedencies.
You need to jcenter back to `android/build.gradle` file at the bottom of allprojects->repositories unit PR is merged, best is to define the package as well because jCenter is in read-only modus and packages will not receive updates anymore there (but do on maven central):
```
allprojects {
    repositories {
		..... # keep all others
		jcenter() {
            content {
                includeModule("com.tom_roush", "pdfbox-android")
            }
        }
	}
}
```

**Comment by ajaybushel** [comment]
For anyone else coming here, just update to the latest version.
