### ISSUE TITLE
Landscape

### ISSUE THREAD

**Issue by waltershub** [christopherdro/react-native-html-to-pdf#67]
how to save the html in landscape?
`<center><h1>Visitor</h1><h1>NAME: Walter Shub</h1><img src="data:image/png;base64,${image}" width="600" height="600" /></center>`

**Comment by esutton** [comment]
@waltershub I wish I had time to clean this up and offer a PR.  

You are welcome to use or fork.  It works on both Android and iOS and supports various page sizes and landscape and portrait.

* https://github.com/esutton/react-native-html-to-pdf

I added options for **page: { size, orientation )** to react-native-html-to-pdf **index.js**

This may have been a bad place to add them.  Not sure.
My goal was to maintain them in a single place in JS rather than have to maintain in both Android and iOS native code.

See **page**:
https://github.com/esutton/react-native-html-to-pdf/blob/master/index.js

````
  onWriteFile = async (fileAttachment, sendCallback) => {
    try {
      if (fileAttachment.mimeType === MimeType.Pdf) {
        const optionsRNHTMLtoPDF = {
          directory: 'docs',
          fileName: fileAttachment.fileBaseName,
          html: fileAttachment.fileData.html,
          page: {
            size: RNHTMLtoPDF.page.size.UsLetter,
            orientation: RNHTMLtoPDF.page.orientation.Landscape,
          },
        };

        await RNHTMLtoPDF.convert(optionsRNHTMLtoPDF);
        // Email the resulting PDF file
        this.onWriteFileComplete(fileAttachment, sendCallback);
        return;
      }

      await RNFS.writeFile(
        fileAttachment.path,
        fileAttachment.fileData,
        fileAttachment.encoding,
      );
      this.onWriteFileComplete(fileAttachment, sendCallback);
    } catch (err) {
      Analytics.logException(`${TAG} onWriteFile`, `Failed to write file: ${fileAttachment.path}`, err);
      Alert.alert(
        `${I18n.t('error')} ${I18n.t('unexpected')}`,
        `${I18n.t('save')}: ${fileAttachment.name}\n${err.message}`,
      );
    }
  };
````

**Comment by MarisTM** [comment]
@esutton Can u provide the file of the example?
Because im trying to write the pdf file using blob but i cant....

**Comment by MarisTM** [comment]
Is this working?

**Comment by rabbanirizwan** [comment]
any solution for this

**Comment by euZebe** [comment]
It seems like just switching `width` and `height` do the trick:
```
  const options: Options = {
    html: MyHTMLContent,
    fileName: myDocName,
    directory: myDirectory,
    base64: true,
    width: 792,
    height: 612,
  }
```

**Comment by J0ANGARFLO** [comment]
> It seems like just switching `width` and `height` do the trick:
> 
> ```
>   const options: Options = {
>     html: MyHTMLContent,
>     fileName: myDocName,
>     directory: myDirectory,
>     base64: true,
>     width: 792,
>     height: 612,
>   }
> ```

Thanks this is the solution
